DROP DATABASE IF EXISTS database_comentarios;

CREATE DATABASE database_comentarios;
USE database_comentarios;

CREATE TABLE comentarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texto_comentario VARCHAR(500) NOT NULL,
    type INT NOT NULL,
    user_id INT NOT NULL, #CHAVE ESTRANGEIRA DO USUARIO QUE POSTOU O COMENTARIO.
    postagem_id INT NOT NULL, #CHAVE ESTRANGEIRA DO POST Q FOI FEITO, PARA DIRECIONAR PARA QUAL FOI, PRECISA SER FEITO UM POST.SQL MAIS TARDE.
    comentario_para INT NULL, #ESTOU EM DÚVIDA NESSE, POIS ELE ACABA SENDO UMA INFORMÇÃO DUPLICADA, BASICAMENTE FAZ O QUE O POSTAGEM_ID FAZ, ENT N SEI SE É NECESSARIO.
    data_postada date NOT NULL
);